/* Autogenerated by png2wx.pl on Sun Jul 29 11:42:51 2012 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_route_pi;

#endif /* ICONS_H */
