#ifndef __Route_piPrefsDialog__
#define __Route_piPrefsDialog__

/**
@file
Subclass of PrefsDialog, which is generated by wxFormBuilder.
*/

#include "UIDialog.h"

//// end generated include

/** Implementing PrefsDialog */
class Route_piPrefsDialog : public PrefsDialog
{
	public:
		/** Constructor */
		Route_piPrefsDialog( wxWindow* parent );
	//// end generated class members
	
};

#endif // __Route_piPrefsDialog__
