#ifndef __Route_piUIDialog__
#define __Route_piUIDialog__

/**
@file
Subclass of UIDialog, which is generated by wxFormBuilder.
*/

#include "UIDialog.h"

//// end generated include

/** Implementing UIDialog */
class Route_piUIDialog : public UIDialog
{
	protected:
		void OnParallelSearchClick( wxCommandEvent& event );
	public:
		/** Constructor */
		Route_piUIDialog( wxWindow* parent );
	//// end generated class members
	
};

#endif // __Route_piUIDialog__

