#ifndef __Route_piMyDialog3__
#define __Route_piMyDialog3__

/**
@file
Subclass of MyDialog3, which is generated by wxFormBuilder.
*/

#include "UIDialog.h"

//// end generated include

/** Implementing MyDialog3 */
class Route_piMyDialog3 : public MyDialog3
{
	public:
		/** Constructor */
		Route_piMyDialog3( wxWindow* parent );
	//// end generated class members
	
};

#endif // __Route_piMyDialog3__
